#!/bin/bash

set -ex

sudo add-apt-repository --yes ppa:juju/stable
sudo apt-get update --yes
sudo apt-get install --yes python-amulet
sudo apt-get install --yes python-neutronclient
sudo apt-get install --yes python-keystoneclient
sudo apt-get install --yes python-novaclient
