#!/usr/bin/python

"""Amulet tests on a basic quantum-gateway deployment on trusty-kilo."""

from basic_deployment import QuantumGatewayBasicDeployment

if __name__ == '__main__':
    deployment = QuantumGatewayBasicDeployment(series='trusty',
                                        openstack='cloud:trusty-kilo',
                                        source='cloud:trusty-updates/kilo')
    deployment.run_tests()
