#!/usr/bin/python

"""Amulet tests on a basic quantum-gateway deployment on utopic-juno."""

from basic_deployment import NeutronGatewayBasicDeployment

if __name__ == '__main__':
    deployment = NeutronGatewayBasicDeployment(series='utopic')
    deployment.run_tests()
