#!/usr/bin/python

"""Amulet tests on a basic quantum-gateway deployment on vivid-kilo."""

from basic_deployment import QuantumGatewayBasicDeployment

if __name__ == '__main__':
    deployment = QuantumGatewayBasicDeployment(series='vivid')
    deployment.run_tests()
