#!/usr/bin/python

"""Amulet tests on a basic quantum-gateway deployment on trusty-mitaka."""

from basic_deployment import NeutronGatewayBasicDeployment

if __name__ == '__main__':
    deployment = NeutronGatewayBasicDeployment(series='trusty',
                                        openstack='cloud:trusty-mitaka',
                                        source='cloud:trusty-updates/mitaka')
    deployment.run_tests()
