#!/usr/bin/python

"""Amulet tests on a basic quantum-gateway deployment on xenial-mitaka."""

from basic_deployment import NeutronGatewayBasicDeployment

if __name__ == '__main__':
    deployment = NeutronGatewayBasicDeployment(series='xenial')
    deployment.run_tests()
