#!/usr/bin/python

"""Amulet tests on a basic quantum-gateway git deployment on trusty-icehouse."""

from basic_deployment import QuantumGatewayBasicDeployment

if __name__ == '__main__':
    deployment = QuantumGatewayBasicDeployment(series='trusty', git=True)
    deployment.run_tests()
