#!/usr/bin/python

"""Amulet tests on a basic quantum-gateway deployment on precise-grizzly."""

from basic_deployment import QuantumGatewayBasicDeployment

if __name__ == '__main__':
    deployment = QuantumGatewayBasicDeployment(series='precise',
                                         openstack='cloud:precise-grizzly',
                                         source='cloud:precise-updates/grizzly')
    deployment.run_tests()
