#!/usr/bin/python

"""Amulet tests on a basic quantum-gateway deployment on precise-havana."""

from basic_deployment import QuantumGatewayBasicDeployment

if __name__ == '__main__':
    deployment = QuantumGatewayBasicDeployment(series='precise',
                                          openstack='cloud:precise-havana',
                                          source='cloud:precise-updates/havana')
    deployment.run_tests()
